### ISSUE TITLE
Presets is not defined

### ISSUE THREAD

**Issue by JanVeb** [closeio/mic-recorder-to-mp3#45]
Uncaught ReferenceError: Presets is not defined
    at index.js:18:1
    at mic-recorder-to-mp3.js?v=0c8867da:9:87
    at node_modules/mic-recorder-to-mp3/dist/index.js (mic-recorder-to-mp3.js?v=0c8867da:10:7)
    at __require (chunk-YT7TXMVK.js?v=0c8867da:5:50)
    at mic-recorder.js:114:12
(anonymous)	@	index.js:18
(anonymous)	@	mic-recorder-to-mp3.js?v=0c8867da:9
node_modules/mic-recorder-to-mp3/dist/index.js	@	mic-recorder-to-mp3.js?v=0c8867da:10
__require	@	chunk-YT7TXMVK.js?v=0c8867da:5
(anonymous)	@	mic-recorder.js:114
Show less

Didnt find any issue related to this

**Comment by JanVeb** [comment]
solved by using       <script src="https://unpkg.com/mic-recorder-to-mp3"></script>
instead of installing it and importing it
import MicRecorder from "mic-recorder-to-mp3";
